### PR TITLE
Offsets for all 64bit iPads,iPods,iPhones iOS 10.2-10.3.1

### PR DESCRIPTION
**Pull request by Mila432**
update 25.08:
the smaller offsets have to be extracted for each kernel, i will upload the new list later

### CODE REVIEW

**Comment by 128keaton** [comment]
Way to go @Mila432!

**Comment by Vitalii2550** [comment]
Yes, sure! Thank you very much for you sent me.
Then how I do it? Please help me!
Sent from my iPhone

On Aug 24, 2017, at 12:46 PM, Keaton Burleson <notifications@github.com<mailto:notifications@github.com>> wrote:


Way to go @Mila432<https://github.com/mila432>!

**Comment by 128keaton** [comment]
Uh, this isn't a support forum. Plus, this isn't a full jailbreak.

**Comment by Jehicular** [comment]
Thank you for saving many many many people a good amount of time yo!

**Comment by MODZ4FUN420** [comment]
Can't wait to see what comes from this!!

**Comment by Mila432** [comment]
main offsets are there but one need to find the smaller ones

**Comment by nkritz** [comment]
do you plan to add offsets for iPhone8,1 (14D27)?

**Pull request closed without merging**
